$ npins get-path hello-world
error:
       … while calling anonymous lambda
         at «string»:1:1:
            1| {pin, path}: ((/*
             | ^
            2|   This file is provided under the MIT licence:

       … while evaluating the attribute 'hello-world.outPath'
         at «string»:116:15:
          115|     in
          116|     spec // { outPath = mayOverride name path; };
             |               ^
          117|

       … from call site
         at «string»:116:25:
          115|     in
          116|     spec // { outPath = mayOverride name path; };
             |                         ^
          117|

       … while calling 'mayOverride'
         at «string»:37:11:
           36|   mayOverride =
           37|     name: path:
             |           ^
           38|     let

       … while evaluating path
         at «string»:44:7:
           43|     if ersatz == "" then
           44|       path
             |       ^
           45|     else

       … from call site
         at «string»:112:11:
          111|         else if spec.type == "Container" then
          112|           mkContainerSource pkgs spec
             |           ^
          113|         else

       … while calling 'mkContainerSource'
         at «string»:215:5:
          214|     pkgs:
          215|     {
             |     ^
          216|       image_name,

       … caused by explicit throw
         at «string»:223:7:
          222|     if pkgs == null then
          223|       builtins.throw "container sources require passing in a Nixpkgs value: https://github.com/andir/npins/blob/master/README.md#using-the-nixpkgs-fetchers"
             |       ^
          224|     else

       error: container sources require passing in a Nixpkgs value: https://github.com/andir/npins/blob/master/README.md#using-the-nixpkgs-fetchers
Error: Could not evaluate pin

Caused by:
    Failed to eval pin: 'hello-world'
    
